export const patients = [
  {
    id: '1',
    name: 'John Smith',
    age: 45,
    gender: 'M',
    mrn: 'MRN001234',
    phone: '(555) 123-4567',
    email: 'john.smith@email.com',
    lastVisit: '2024-07-15',
    conditions: ['Hypertension', 'Type 2 Diabetes'],
    activeConditions: 2,
  },
  {
    id: '2',
    name: 'Sarah Johnson',
    age: 32,
    gender: 'F',
    mrn: 'MRN001235',
    phone: '(555) 987-6543',
    email: 'sarah.johnson@email.com',
    lastVisit: '2024-07-16',
    conditions: ['Migraine'],
    activeConditions: 1,
  },
  {
    id: '3',
    name: 'Michael Davis',
    age: 58,
    gender: 'M',
    mrn: 'MRN001236',
    phone: '(555) 456-7890',
    email: 'michael.davis@email.com',
    lastVisit: '2024-07-10',
    conditions: ['Hyperlipidemia', 'Osteoarthritis'],
    activeConditions: 2,
  },
];

export const notes = [
  {
    id: '1',
    patientName: 'John Smith',
    specialty: 'Cardiology',
    date: '2024-07-18',
    time: '10:30 AM',
    status: 'completed',
    codes: ['120.9', '93000'],
    duration: '15 min',
    provider: 'Dr. Chen',
  },
  {
    id: '2',
    patientName: 'Sarah Johnson',
    specialty: 'Pediatrics',
    date: '2024-07-18',
    time: '09:15 AM',
    status: 'draft',
    codes: ['Z00.00'],
    duration: '20 min',
    provider: 'Dr. Martinez',
  },
  {
    id: '3',
    patientName: 'Michael Davis',
    specialty: 'Neurology',
    date: '2024-07-17',
    time: '02:45 PM',
    status: 'completed',
    codes: ['Z00.129', '90460'],
    duration: '25 min',
    provider: 'Dr. Williams',
  },
];